pipeline:
  identifier: Build_usmanakramb_jhttp_demo_1748665667936
  name: Build jhttp-demo
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1748651591728
        repoName: usmanakramb/jhttp-demo
  stages:
    - stage:
        name: build
        identifier: build
        template:
          templateRef: jhttpbuildtemplate
          versionLabel: "0.1"
    - stage:
        name: deploy
        identifier: deploy
        tags: {}
        template:
          templateRef: jhttpdeploytemplate
          versionLabel: "0.1"
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: <+input>
                          sources: <+input>
