pipeline:
  identifier: Build_usmanakramb_jhttp_demo_1748665667936
  name: Build jhttp-demo
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1748651591728
        repoName: usmanakramb/jhttp-demo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_java_app
                  name: Build Java App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
              - step:
                  type: Run
                  name: RunTests
                  identifier: Run_Tests
                  spec:
                    command: mvn test
                    shell: Sh
                    connectorRef: account.harnessImage
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: account.harnessImage
                    repo: usmanakramb/jhttp-demo
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            arch: Arm64
            os: MacOS
          runtime:
            spec: {}
            type: Docker
        type: CI
